name: Run Selenium Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Install Chromedriver
      run: npm install chromedriver --chromedriver_version=LATEST
      
    - name: Install system dependencies
      run: |
        sudo apt -y update 
        sudo apt -y install google-chrome-stable  
        

    - name: Start application & run tests
      run: |
        npm start & npm test