name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: download chrome
      run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  
    - name: Install chrome
      run: sudo dpkg -i google-chrome-stable_current_amd64.deb

    - name: Install system dependencies
      run: sudo apt-get install -f

    - name: Install dependencies
      run: npm install
      
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 120

    - name: Start Web Server and run test
      run: npm start & npm test