name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: update apt
      run: sudo apt -y update 
  
    - name: Install chrome
      run: sudo apt -y install google-chrome-stable

    - name: Install dependencies
      run: npm install

    - name: Start Web Server and run test
      run: npm start & npm test